<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_en       Sign in to WebClient         _d0c21e</name>
   <tag></tag>
   <elementGuidId>297074dc-1e52-47ce-b0ca-033b396d1666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.o-card.c-card.is-loading.is-previous.on-destroy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/main/form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>77f087da-e11b-484c-bb6c-c148966fbb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component</name>
      <type>Main</type>
      <value>templates-card~sign-in-1</value>
      <webElementGuid>8e191337-7592-46bf-96b4-f852b3c6ecba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-card c-card is-loading is-previous on-destroy</value>
      <webElementGuid>828bfb62-0f7b-4d66-a111-d9d20d3f464f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hook</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>3ddc1506-03d9-4bb5-b66b-5b4b3163ee0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>19dfc062-7cf1-47be-a29d-12da1c0b5aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        en       Sign in to WebClient                 Email address     Next     </value>
      <webElementGuid>ec3d253b-4a94-4af1-82ba-7f9f3d2ab0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[@class=&quot;o-external__main&quot;]/form[@class=&quot;o-card c-card is-loading is-previous on-destroy&quot;]</value>
      <webElementGuid>a8c60a24-e79c-4d95-8f1b-4ec647254e48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/form</value>
      <webElementGuid>88f3b2f3-b25a-4d5b-ad5f-a75c1a93adcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>ebed39c9-4652-4b3d-a91d-ba01f924126f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = '        en       Sign in to WebClient                 Email address     Next     ' or . = '        en       Sign in to WebClient                 Email address     Next     ')]</value>
      <webElementGuid>9e3c2f62-0cb9-432d-9156-73915ef1cc96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
