<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in to WebClient_email-address</name>
   <tag></tag>
   <elementGuidId>5268a09b-ca1d-404c-9857-ef1ba7425a70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email-address&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email-address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b3f2570-8f09-4d7b-b190-753a706e401e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component</name>
      <type>Main</type>
      <value>atoms-element-input-1</value>
      <webElementGuid>c2fcabe6-798d-4f0e-b59b-0f000a1d908c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> o-form__element</value>
      <webElementGuid>ebbf6467-6605-4fd0-a2c8-fa7937cff996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e2de124d-171c-4f9e-a46c-6fb3ef5a0334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email-address</value>
      <webElementGuid>01d01cfc-bf78-4308-9106-17ff0f713395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hook</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3d32e369-5471-4289-8cd2-40c0eda244a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[@class=&quot;o-external__main&quot;]/form[@class=&quot;o-card c-card&quot;]/div[@class=&quot;o-card__main&quot;]/div[@class=&quot;o-card__content&quot;]/section[@class=&quot;o-card__section  o-card__section--form&quot;]/label[@class=&quot;o-input o-form__object molecules-input&quot;]/input[@class=&quot;o-form__element&quot;]</value>
      <webElementGuid>76896e97-ab65-4241-a510-8afcefe30b9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email-address']</value>
      <webElementGuid>1445ea61-8f2d-4118-998e-24fcf52f6ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/form/div/div/section[2]/label/input</value>
      <webElementGuid>1df828fe-787c-423e-a14b-c0d7e438609b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c35297e0-1b47-461c-8739-45bf15993692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email-address']</value>
      <webElementGuid>80d0ad92-9762-425d-8d50-e0729a13d54c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
