<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Next</name>
   <tag></tag>
   <elementGuidId>0c1d56c1-9dbc-4b9f-bda8-4bafb0b7e090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;next&quot;] > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/main/form/div/div/section[3]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Next&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3bf448af-ae24-4a26-a201-406fb7eafdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>6f7b15b8-52c0-4f12-83f6-8ac5d3909e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[@class=&quot;o-external__main&quot;]/form[@class=&quot;o-card c-card&quot;]/div[@class=&quot;o-card__main&quot;]/div[@class=&quot;o-card__content&quot;]/section[@class=&quot;o-card__section  o-card__section--default&quot;]/div[@class=&quot;o-button o-form__object  o-button--block  o-button--primary&quot;]/button[1]/span[1]</value>
      <webElementGuid>4c3baeef-d6c9-48e8-b337-655a02feaa08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/form/div/div/section[3]/div/button/span</value>
      <webElementGuid>b1572477-e647-488a-9d3b-42f9590e5fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/following::span[1]</value>
      <webElementGuid>41e27699-5914-411c-b083-79489e71ec1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to WebClient'])[1]/following::span[2]</value>
      <webElementGuid>3d782f27-9ce0-4724-a00c-8e37a2d2a3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.icewarp.com'])[1]/preceding::span[1]</value>
      <webElementGuid>7db77b34-bc52-4765-8491-2bcdc868e03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>50aec395-989f-4d4b-8b77-6f8338f3033e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>aea89f1f-5634-4040-990f-6fb21673a427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>5b884283-5b6e-469f-aefd-de847304512a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
